on:
  push:
    branches:
      - main
      - master
permissions:
  contents: write
  pull-requests: write
name: test-coverage.yaml
jobs:
  coverage:
    name: Coverage report
    uses: NovoNordisk-OpenSource/r.workflows/.github/workflows/coverage.yaml@main
    secrets: inherit
    with:
      use_codecov: true
